### ISSUE TITLE
Add new message with client metadata

### ISSUE THREAD

**Issue by follesoe** [BluEye-Robotics/ProtocolDefinitions#18]
We should add a new message definition with information about the client, that can be published from the client when connecting.

The information should include:

- Client type (SDK, Blueye App, other)
- Client version
- Device type (Manufacturer and model)
- Platform (Operating system, such as iOS/Android/Windows)
- Platform version

This way, every dive log would include information about any connected client for a given dive. This would greatly help with debugging, as we could know what type of client was used for a particular dive.

**Comment by erlenner** [comment]
Fixed in b3fd05c67ab7a99a4547d3df55b0cc8fd44f345d
