### ISSUE TITLE
Protocol revision

### ISSUE THREAD

**Issue by jandren** [BluEye-Robotics/ProtocolDefinitions#3]
Just collect ideas for future protocol update

Would be good to have in the logs:
Type of device used, pilot and buddies
Calibrated gyro
Calibrated acc
Thrust setpoint
Dropped frames?
CPU usage
RAM usage

**Comment by jandren** [comment]
Add final line telling us if shutdown was intentional or not.
I.e. Fault or loss of battery will not end with some specific information
Correct shutdown will write one final line or just set some bit somewhere that later can be appended to the log files.

(Sitting with a support case where the customer claims that it shut down while diving but it just seems to be loss of connection to the app, logging this information would help a lot in debugging)

**Comment by jandren** [comment]
add /hmi/watchdog or similar connection metric an improvement would be if we could tell if it is an intentional end dive or loss.
Simplifies the process of seeing stability of link and helps in debugging.
Consider having ping times as well as realtime link metric (now that iperf only runs when video streams are connected).

**Comment by jandren** [comment]
Lost connection, time and why its raised.
Probably also log the watchdog message that counts up (would show app connection)

**Comment by johannesschrimpf** [comment]
Followed up in https://github.com/BluEye-Robotics/ProtocolDefinitions/pull/14
